# paasta-pinpoint-vsphere 설정 파일 내용
name: paasta-pinpoint-service                           # 서비스 배포이름(필수)
director_uuid: 93b19179-c3d8-456b-9c52-5f0fe1adea0e     # bosh status 에서 확인한 Director UUID을 입력(필수)

releases:
- name: paasta-pinpoint                                     # 서비스 릴리즈 이름(필수)
  version: 2.0                                              # 서비스 릴리즈 버전(필수):latest 시 업로드된 서비스 릴리즈 최신버전

compilation:                         # 컴파일시 필요한 가상머신의 속성(필수)
  workers: 1                         # 컴파일 하는 가상머신의 최대수(필수)
  network: default                   # Networks block에서 선언한 network 이름(필수)
  reuse_compilation_vms: true
  cloud_properties:   # 컴파일 VM을 만드는 데 필요한 IaaS의 특정 속성 (instance_type, availability_zone), 직접 cpu,disk,ram 사이즈를 넣어도 됨
    availability_zone: ap-northeast-2a
    instance_type: c4.large

update:
  canaries: 1                            # canary 인스턴스 수(필수)
  canary_watch_time: 120000              # canary 인스턴스가 수행하기 위한 대기 시간(필수)
  update_watch_time: 120000              # non-canary 인스턴스가 수행하기 위한 대기 시간(필수)
  max_in_flight: 8                       # non-canary 인스턴스가 병렬로 update 하는 최대 개수(필수)

networks:                                # 네트워크 블록에 나열된 각 서브 블록이 참조 할 수있는 작업이 네트워크 구성을 지정, 네트워크 구성은 네트워크 담당자에게 문의 하여 작성 요망
- name: default
  type: manual
  subnets:
  - range: 10.0.0.0/24
    gateway: 10.0.0.1
    dns: [10.0.0.6, 8.8.8.8]                      # DNS 정보
    reserved: ["10.0.0.2 - 10.0.0.140"]            # 설치시 제외할 IP 설정
    static: ["10.0.0.141 - 10.0.0.200"]
    cloud_properties:
      subnet: subnet-cdfc80a4                     # AWS subnet id
      security_groups:
        - psta-cf-security
        - psta-bosh-security

#- name: public_network    #퍼블릭 네트워크
#  type: vip
#  cloud_properties: {}


resource_pools:                # 배포시 사용하는 resource pools를 명시하며 여러 개의 resource pools 을 사용할 경우 name 은 unique 해야함(필수)
- name: pinpoint_small         # 고유한 resource pool 이름
  network: default
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent      # stemcell 이름(필수)
    version: 3309                                   # stemcell 버전(필수)
  cloud_properties:         # 컴파일 VM을 만드는 데 필요한 IaaS의 특정 속성을 설명 (instance_type, availability_zone), 직접 cpu, disk, 메모리 설정가능
    instance_type: t2.small
    availability_zone: ap-northeast-2a
- name: pinpoint_medium
  network: default
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent      # stemcell 이름(필수)
    version: 3309                                   # stemcell 버전(필수)
  cloud_properties:         # 컴파일 VM을 만드는 데 필요한 IaaS의 특정 속성을 설명 (instance_type, availability_zone), 직접 cpu, disk, 메모리 설정가능
    instance_type: t2.small
    availability_zone: ap-northeast-2a

jobs:
- name: h_slave                           #작업 이름(필수)
  template: h_slave                       # job template 이름(필수)
  instances: 2                            # job 인스턴스 수(필수)     
  resource_pool: pinpoint_small           # resource_pools block에 정의한 resource pool 이름(필수)
  networks:                               # 네트워크 구성정보
  - name: default                         # Networks block에서 선언한 network 이름(필수)
    static_ips:                           # 사용할 IP addresses 정의(필수): Pinpoint 서버 IP
    - 10.0.0.190
    - 10.0.0.191
- name: h_secondary                       #작업 이름(필수)
  template: h_secondary                   # job template 이름(필수)
  instances: 1                            # job 인스턴스 수(필수)
  resource_pool: pinpoint_small           # resource_pools block에 정의한 resource pool 이름(필수)
  networks:                               # 네트워크 구성정보
  - name: default                         # Networks block에서 선언한 network 이름(필수)
    static_ips:                           # 사용할 IP addresses 정의(필수): Pinpoint 서버 IP
    - 10.0.0.176
- name: h_master                          #작업 이름(필수)
  template: h_master                      # job template 이름(필수)
  instances: 1                            # job 인스턴스 수(필수)
  resource_pool: pinpoint_medium          # resource_pools block에 정의한 resource pool 이름(필수)
  networks:                               # 네트워크 구성정보          
  - name: default                         # Networks block에서 선언한 network 이름(필수)
    static_ips:                           # 사용할 IP addresses 정의(필수): Pinpoint 서버 IP  
    - 10.0.0.175
- name: h_master_register                 #작업 이름(필수)
  template: h_master_register             # job template 이름(필수)
  instances: 1                            # job 인스턴스 수(필수)
  lifecycle: errand                       # resource_pools block에 정의한 resource pool 이름(필수)   
  resource_pool: pinpoint_small           # 네트워크 구성정보
  networks:                               # Networks block에서 선언한 network 이름(필수)
  - name: default
- name: collector                          #작업 이름(필수)
  template: collector                      # job template 이름(필수)
  instances: 2                             # job 인스턴스 수(필수)
  resource_pool: pinpoint_medium           # resource_pools block에 정의한 resource pool 이름(필수)
  networks:                                # 네트워크 구성정보
  - name: default                          # Networks block에서 선언한 network 이름(필수)
    static_ips:                            # 사용할 IP addresses 정의(필수): Pinpoint 서버 IP
    - 10.0.0.145
    - 10.0.0.146
- name: haproxy_webui
  template: haproxy_webui
  instances: 1
  resource_pool: pinpoint_small
  networks:
  - name: default
    static_ips:                           # 사용할 IP addresses 정의(필수): Pinpoint 서버 IP
    - 10.0.0.178
#  - name: public-network                          
#    default:
#    - dns
#    - gateway
#    static_ips: 115.68.46.182
- name: webui                              #작업 이름(필수)
  template: webui                          # job template 이름(필수)
  instances: 2                            # job 인스턴스 수(필수)
  resource_pool: pinpoint_small            # resource_pools block에 정의한 resource pool 이름(필수)
  networks:                                # 네트워크 구성정보
  - name: default                          # Networks block에서 선언한 network 이름(필수)
    static_ips:                            # 사용할 IP addresses 정의(필수): Pinpoint 서버 IP                          
    - 10.0.0.179
    - 10.0.0.180
- name: pinpoint_broker                    #작업 이름(필수)
  template: broker                         # job template 이름(필수)
  instances: 1                             # job 인스턴스 수(필수)
  resource_pool: pinpoint_small            # resource_pools block에 정의한 resource pool 이름(필수)
  networks:                                # 네트워크 구성정보
  - name: default                          # Networks block에서 선언한 network 이름(필수)
    static_ips:                            # 사용할 IP addresses 정의(필수): Pinpoint 서버 IP                          
    - 10.0.0.182
properties:                                # Pinpoint 설정정보
  master:                                  # Pinpoint master 설정정보
    host_name: h-master                    # Pinpoint master name
    host_ip: 10.0.0.175                    # Pinpoint master IP
    port: 9000                             # Pinpoint master port
    http_port: 50070                       # Pinpoint master http port
    replication: 2                         # Pinpoint master 복제개수
    tcp_listen_port: 29994                 # Pinpoint master tcp port
    udp_stat_listen_port: 29995            # Pinpoint master udp stat port
    udp_span_listen_port: 29996            # Pinpoint master udp span port
  broker:                                  # Pinpoint broker 설정정보
    collector_ips:                         # Pinpoint collector ip 설정정보
    - 10.0.0.145
    - 10.0.0.146
    collector_tcp_port: 29994              # Pinpoint collector tcp port 설정정보                        # 
    collector_stat_port: 29995             # Pinpoint collector stat port 설정정보
    collector_span_port: 29996             # Pinpoint collector span port 설정정보
    dashboard_uri: http://115.68.46.182:80/#/main   # Pinpoint dashboard url 설정정보
  secondary:                               # Pinpoint secondary 설정정보
    host_name: h-secondary                 # Pinpoint secondary name
    host_ip: 10.0.0.176                    # Pinpoint secondary IP
    http_port: 50090                       # Pinpoint secondary port
  yarn:                                    # Pinpoint yarn 설정정보      
    host_name: h-master                    # Pinpoint yarn name
    host_ip: 10.0.0.175                    # Pinpoint yarn ip
    resource_tracker_port: 8025            # Pinpoint yarn resource_tracker_port
    scheduler_port: 8030                   # Pinpoint yarn scheduler_port
    resourcemanager_port: 8040             # Pinpoint yarn resourcemanager_port
  slave:                                   # Pinpoint slave 설정정보      
    host_names:                            # Pinpoint slave name
    - h-slave0
    - h-slave1
    host_ips:                              # Pinpoint slave ip 
    - 10.0.0.190
    - 10.0.0.191
  collector:                               # Pinpoint collector 설정정보  
    host_names:                            # Pinpoint collector host name
    - h-collector0
    - h-collector1
    host_ips:                              # Pinpoint collector host IP
    - 10.0.0.145
    - 10.0.0.146
  haproxy:                                 # Pinpoint haproxy 설정정보  
    host_name: haproxy-webui               # Pinpoint haproxy host name
    host_ip: 10.0.0.178                    # Pinpoint haproxy host IP
    http_port: 80                          # Pinpoint haproxy host port
  webui:                                   # Pinpoint webui 설정정보  
    host_names:                            # Pinpoint webui host name
    - h-webui0
    - h-webui1
    host_ips:                               # Pinpoint webui host IP
    - 10.0.0.179
    - 10.0.0.180